apiVersion: v1
kind: Namespace
metadata:
    name: {{ .Values.nodeName | quote}}
    annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-weight": "-5"  # Ensures this runs before other hooks