apiVersion: v1
kind: Service
metadata:
  name: training-worker
  namespace: {{ .Values.nodeName | quote }}
spec:
  selector:
    app: training-worker
  ports:
  - port: 5000
    targetPort: 5000
  clusterIP: None