apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    meta.helm.sh/release-name: oasees-user
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  name: oasees-agent
  namespace: default
spec:
  selector:
    matchLabels:
      component: oasees-agent
  template:
    metadata:
      labels:
        component: oasees-agent
    spec:
      containers:
      - name: oasees-agent
        image: oasees/oasees-agent:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName