apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: oasees-user
    meta.helm.sh/release-namespace: default
  name: cluster-backend
  labels:
    app.kubernetes.io/managed-by: Helm
    component: cluster-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cluster-backend
  template:
    metadata:
      labels:
        component: cluster-backend
    spec:
      serviceAccountName: notebook-sa
      containers:
      - name: cluster-backend
        image: oasees/cluster-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: oasees-user
    meta.helm.sh/release-namespace: default
  labels:
    # app.kubernetes.io/managed-by: Helm
    component: cluster-backend
  name: cluster-backend
spec:
  type: NodePort
  selector:
    component: cluster-backend
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30021