apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-backend-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: oasees-user
    meta.helm.sh/release-namespace: default
  name: cluster-backend
  labels:
    app.kubernetes.io/managed-by: Helm
    component: cluster-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cluster-backend
  template:
    metadata:
      labels:
        component: cluster-backend
    spec:
      serviceAccountName: notebook-sa
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
      - name: cluster-backend
        image: oasees/cluster-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: DB_PATH
          value: "/data/devices.db"
        volumeMounts:
        - name: sqlite-storage
          mountPath: /data
      volumes:
      - name: sqlite-storage
        persistentVolumeClaim:
          claimName: cluster-backend-pvc

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: oasees-user
    meta.helm.sh/release-namespace: default
  labels:
    # app.kubernetes.io/managed-by: Helm
    component: cluster-backend
  name: cluster-backend
spec:
  type: NodePort
  selector:
    component: cluster-backend
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30021