apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-backend
  labels:
    app: cluster-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-backend
  template:
    metadata:
      labels:
        app: cluster-backend
    spec:
      serviceAccountName: notebook-sa
      containers:
      - name: cluster-backend
        image: oasees/cluster-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: cluster-backend
spec:
  type: NodePort
  selector:
    app: cluster-backend
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30021