apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    meta.helm.sh/release-name: oasees-user
    meta.helm.sh/release-namespace: default
  name: oasees-device-plugin
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    app: oasees-device-plugin
spec:
  selector:
    matchLabels:
      app: oasees-device-plugin
  template:
    metadata:
      labels:
        app: oasees-device-plugin
    spec:
      containers:
      - name: oasees-device-plugin
        resources:
          requests:
            cpu: 50m
            memory: 250Mi
          limits:
            cpu: 50m
            memory: 250Mi
        image: "ghcr.io/oasees/device-plugin:latest"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
