apiVersion: apps/v1
kind: Deployment
metadata:
  name: oasees-ide
  labels:
    app: oasees-ide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oasees-ide
  template:
    metadata:
      labels:
        app: oasees-ide
    spec:
      containers:
      - name: oasees-ide
        image: ghcr.io/achilleaseconomopoulos/oasees-ide:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: oasees-ide
spec:
  type: NodePort
  selector:
    app: oasees-ide
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001