apiVersion: apps/v1
kind: Deployment
metadata:
  name: oasees-ipfs
  labels:
    app: oasees-ipfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oasees-ipfs
  template:
    metadata:
      labels:
        app: oasees-ipfs
    spec:
      containers:
      - name: oasees-ipfs
        image: ghcr.io/achilleaseconomopoulos/ipfs-node:latest
        ports:
        - containerPort: 4001
          hostPort: 4001
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 5001
          hostPort: 5001
        env:
        - name: MASTER_NODE
          value: "10.160.3.172"
        - name: MASTER_PEER_ID
          value: "12D3KooWG51xC8aADbouSfTbqCfAjUMbWiiWeVFSnBcqby31bTXE"
        - name: EXPOSED_IP
          value: {{ .Values.exposedIP | default "localhost" | quote }}

---

apiVersion: v1
kind: Service
metadata:
  name: oasees-ipfs
spec:
  selector:
    app: oasees-ipfs
  ports:
    - port: 5001
      targetPort: 5001
      name: api
    - port: 8080
      targetPort: 8080
      name: gateway