apiVersion: v1
kind: ServiceAccount
metadata:
  name: notebook-sa
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notebook-pod-manager
  namespace: default
subjects:
  - kind: ServiceAccount
    name: notebook-sa
    namespace: default
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: notebook-node-reader
subjects:
  - kind: ServiceAccount
    name: notebook-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oasees-notebook
  namespace: default
  labels:
    component: oasees-notebook
spec:
  selector:
    matchLabels:
      app: oasees-notebook
  template:
    metadata:
      labels:
        app: oasees-notebook
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      serviceAccountName: notebook-sa
      containers:
      - name: oasees-notebook
        image: oasees/oasees-notebook:latest
        command: ["/usr/local/bin/init-oasees-notebook.sh"]
        ports:
        - containerPort: 8081
      nodeSelector:
        kubernetes.io/arch: amd64
---
apiVersion: v1
kind: Service
metadata:
  name: oasees-notebook
  namespace: default
  labels:
    component: oasees-notebook
spec:
  type: NodePort
  ports:
  - port: 8081
  selector:
    app: oasees-notebook