apiVersion: apps/v1
kind: Deployment
metadata:
  name: oasees-portal
  labels:
    app: oasees-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oasees-portal
  template:
    metadata:
      labels:
        app: oasees-portal
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
      - name: oasees-portal
        imagePullPolicy: Always
        image: oasees/oasees-portal:latest
        command: [ "/bin/sh", "-c" ]
        args:
          - |
            echo "REACT_APP_EXPOSED_IP=$REACT_APP_EXPOSED_IP" > .env 
            npm start
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_EXPOSED_IP
          value: "10.160.1.209"
        - name: REACT_APP_BLOCKCHAIN_HOST
          value: "10.160.3.172"
---

apiVersion: v1
kind: Service
metadata:
  name: oasees-portal
spec:
  type: NodePort
  selector:
    app: oasees-portal
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000