apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: oasees-user

  name: oasees-portal
  labels:
    app.kubernetes.io/managed-by: Helm
    component: oasees-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      component: oasees-portal
  template:
    metadata:
      labels:
        component: oasees-portal
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
      - name: oasees-portal
        # imagePullPolicy: Always
        imagePullPolicy: IfNotPresent

        image: oasees/oasees-portal:latest
        command: [ "/bin/sh", "-c" ]
        args:
          - |
            echo "REACT_APP_EXPOSED_IP=$REACT_APP_EXPOSED_IP" > .env 
            npm start
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_EXPOSED_IP
          value: {{ .Values.exposedIP | default "localhost" | quote }}
        - name: REACT_APP_BLOCKCHAIN_HOST
          value: "10.160.3.172"
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: oasees-user
  name: oasees-portal
  labels:
    # app.kubernetes.io/managed-by: Helm
    component: oasees-portal
spec:
  type: NodePort
  selector:
    component: oasees-portal
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000