apiVersion: apps/v1
kind: Deployment
metadata:
  name: oasees-portal
  labels:
    app: oasees-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oasees-portal
  template:
    metadata:
      labels:
        app: oasees-portal
    spec:
      containers:
      - name: oasees-portal
        image: ghcr.io/achilleaseconomopoulos/oasees-portal:latest
        command: [ "/bin/sh", "-c", "npm start" ]
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_EXPOSED_IP
          value: {{ .Values.exposedIP | default "localhost" | quote }}
        - name: REACT_APP_BLOCKCHAIN_HOST
          value: {{ .Values.blockchainHost | default "10.160.3.172:8545" | quote }}
        - name: REACT_APP_BLOCK_EXPLORER_API
          value: "10.160.3.172:8082/api/v2"
        - name: REACT_APP_MARKETPLACE_ADDRESS
          value: {{ .Values.marketplaceAddress | default "0x5FbDB2315678afecb367f032d93F642f64180aa3" | quote }}
        - name: REACT_APP_NFT_ADDRESS
          value: {{ .Values.nftAddress | default "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" | quote }}

---

apiVersion: v1
kind: Service
metadata:
  name: oasees-portal
spec:
  type: NodePort
  selector:
    app: oasees-portal
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000