apiVersion: apps/v1
kind: Deployment
metadata:
  name: oasees-solidity-ide
  annotations:
    meta.helm.sh/release-name: oasees-user
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    component: oasees-solidity-ide
spec:
  replicas: 1
  selector:
    matchLabels:
      component: oasees-solidity-ide
  template:
    metadata:
      labels:
        component: oasees-solidity-ide
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
      - name: oasees-solidity-ide
        image: oasees/solidity-ide:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: oasees-solidity-ide
  annotations:
    meta.helm.sh/release-name: oasees-user
    meta.helm.sh/release-namespace: default
  labels:
    # app.kubernetes.io/managed-by: Helm
    component: oasees-solidity-ide
spec:
  type: NodePort
  selector:
    component: oasees-solidity-ide
  ports:
    - port: 3001
  selector:
    component: oasees-solidity-ide