apiVersion: apps/v1
kind: Deployment
metadata:
  name: oasees-solidity-ide
  labels:
    component: oasees-solidity-ide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oasees-solidity-ide
  template:
    metadata:
      labels:
        app: oasees-solidity-ide
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
      - name: oasees-solidity-ide
        image: oasees/solidity-ide:latest
        ports:
        - containerPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: oasees-solidity-ide
  labels:
    component: oasees-solidity-ide
spec:
  type: NodePort
  selector:
    app: oasees-solidity-ide
  ports:
    - port: 3001
  selector:
    app: oasees-solidity-ide